### ISSUE TITLE
Problems abount the Prog-X parameter settings for homography and two-view motion

### ISSUE THREAD

**Issue by ZizhuoLi** [danini/progressive-x#5]
Dear @danini, thanks for your awesome work :)

I am trying your code but can not reproduce the results as the paper presented.  I guess it is caused by the parameter setting， because in the source codes, I can not find the setting of label cost (w_l). I hope you can give me some suggestions.

Thanks!

Best regards

**Comment by danini** [comment]
This might be a bit late, but you can find codes for reproducing similar results as in the paper at: https://github.com/danini/progressive-x/tree/master/dataset_comparison
